## Build Spring Boot
FROM maven:3.9.0-eclipse-temurin-19 AS springboot

WORKDIR /app

COPY server/mvnw .
COPY server/mvnw.cmd .
COPY server/pom.xml .
COPY server/src ./src

RUN mvn package -Dmaven.test.skip=true

# Copy the final Jar file
FROM eclipse-temurin:19-jre

WORKDIR /app

COPY --from=springboot /app/target/server-0.0.1-SNAPSHOT.jar server.jar

ARG TIH_API_KEY
ARG SPACES_ACCESS_KEY
ARG SPACES_SECRET_KEY
ARG SPRING_DATASOURCE_URL
ARG SPRING_REDIS_HOST
ARG SPRING_REDIS_PORT
ARG SPRING_REDIS_PASSWORD

ENV TIH_API_KEY=${TIH_API_KEY}
ENV SPACES_ACCESS_KEY=${SPACES_ACCESS_KEY}
ENV SPACES_SECRET_KEY=${SPACES_SECRET_KEY}
ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
ENV SPRING_REDIS_HOST=${SPRING_REDIS_HOST}
ENV SPRING_REDIS_PORT=${SPRING_REDIS_PORT}
ENV SPRING_REDIS_PASSWORD=${SPRING_REDIS_PASSWORD}

ENV PORT=8080

EXPOSE ${PORT}

ENTRYPOINT java -Dserver.port=${PORT} -jar server.jar